# Generated by Django 5.2.8 on 2025-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa usługi')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Np. 60 dla godziny, 480 dla całego dnia', verbose_name='Czas trwania [min]')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena bazowa')),
            ],
        ),
    ]
