# Generated by Django 5.2.8 on 2025-11-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Początek')),
                ('end', models.DateTimeField(verbose_name='Koniec')),
                ('status', models.CharField(choices=[('scheduled', 'Zaplanowana'), ('in_progress', 'W realizacji'), ('done', 'Zakończona'), ('cancelled', 'Anulowana')], default='scheduled', max_length=20, verbose_name='Status')),
                ('mileage_at_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Przebieg przy wizycie')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vehicles.vehicle')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.workstation')),
            ],
        ),
    ]
