# Generated by Django 5.2.8 on 2025-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Czy wysłano już przypomnienie o tej wizycie', verbose_name='Przypomnienie wysłane'),
        ),
    ]
