# Generated by Django 5.2.8 on 2025-11-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TireSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Numer naklejony na komplet/regal', max_length=50, unique=True, verbose_name='Identyfikator kompletu')),
                ('description', models.CharField(blank=True, help_text='Np. 205/55 R16 zimowe', max_length=200, verbose_name='Opis')),
                ('location', models.CharField(blank=True, help_text='Regał / sektor / półka', max_length=100, verbose_name='Miejsce składowania')),
                ('is_in_storage', models.BooleanField(default=True, verbose_name='W magazynie')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_sets', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_sets', to='vehicles.vehicle')),
            ],
        ),
    ]
