# Generated by Django 5.2.8 on 2025-11-11 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireset',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_sets', to=settings.AUTH_USER_MODEL, verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='tireset',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_sets', to='vehicles.vehicle', verbose_name='Pojazd'),
        ),
    ]
