# Generated by Django 5.2.8 on 2025-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Opcjonalne zdjęcie pojazdu', null=True, upload_to='vehicles/', verbose_name='Zdjęcie'),
        ),
    ]
